 # INTRODUCTION TO NUMPY FOR PYTHON MATRICES #
 

In [1]:
# Importing the numpy package to work with #

import numpy as np

In [8]:
# defining arrays in 1-dimensions #

one_D = np.array([2,7,9])
print(one_D)

[2 7 9]


In [16]:
# defining the matrices in one direction #

increment_of_3 = np.array([1,5,7])
print(increment_of_3)

[1 5 7]


In [17]:
# usung the np.arange fuction to defime, creating an array of 3 integers starting from 0 #

a = np.arange(5)
print(a)

[0 1 2 3 4]


In [19]:

# create an array with an interval and an increment of 3  #

b= np.arange(3,30,3)
print(b)

[ 3  6  9 12 15 18 21 24 27]


In [21]:
# using the np.linspace to define a lager matrix #

c = np.linspace(0,100,5)
print(c)

[  0.  25.  50.  75. 100.]


In [3]:
# Since the characters generated are floating numbers,we might want to change the data type to integers, you need to set the dtype to int. #

c_int = np.linspace(0,100,5, dtype=int )
print(c_int)

[  0  25  50  75 100]


 # Multidimensional Arrays #

In [9]:
# Create a 2 dimensional array (2-D)
two_D_arr = np.array([[1,2,3], [4,5,6]])
print(two_D_arr)

[[1 2 3]
 [4 5 6]]


In [20]:
# creating a 1_D array

one_D_arr = np.array([1,2,3,4,5,6])

# creating a 2_D array from 1_D array

multi_D_arr = np.reshape( one_D_arr ,  #array to be reshaped
                        (2,3)      # dimension of array
                        )
#print the new 2 _rows, 3_columns array
print(multi_D_arr)

[[1 2 3]
 [4 5 6]]


In [27]:
# creating a 1_D array

one_D_arr = np.array([1,2,3,4,5,6])

# creating a 2_d array

two_d_arr = np.reshape(one_d_arr ,
                       (2,3)
                        )
print(two_d_arr)

[[1 2 3]
 [4 5 6]]


In [28]:
# creating a 1_D array

one_D_arr = np.array([1,2,3,4,5,6,7,8,9])

# creating a 3_D array from 1_D array

multi_D_arr = np.reshape( 
    one_D_arr ,  #array to be reshaped
    (3,3)     # dimension of array
                        )
#print the new 2 _rows, 3_columns array
print(multi_D_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Finding size, shape and dimension

In [30]:
# finding the dimension of the array

multi_D_arr.ndim

2

In [31]:
# finding the size of the array
# returns the total number of elements in the array

multi_D_arr.size

9

In [33]:
# finding the shape of the array
# returns the a 3 by 3 array

multi_D_arr.shape

(3, 3)

#  Array math operations

In [2]:
# addition of 1_D arrays
# defining the arrays

arr_1 = np.array([2,4,6])
arr_2 = np.array([8,3,9])

# addition of the arrays

add_arr = arr_1 + arr_2

# print results

print(add_arr)



[10  7 15]


In [3]:
# subtracting the arrays

subtr_arr = arr_1 - arr_2

# print results

print(subtr_arr)

[-6  1 -3]


# Multiplying vector with a scalar (broadcasting)

Suppose you need to convert miles to kilometers. To do so, you can use the NumPy array functions that you've learned so far. You can do this by carrying out an operation between an array (miles) and a single number (the conversion rate which is a scalar). Since, 1 mile = 1.6 km, NumPy computes each multiplication within each cell.

This concept is called broadcasting, which allows you to perform operations specifically on arrays of different shapes

In [5]:
vector = np.array([2,4,6])
vector * 1.9

array([ 3.8,  7.6, 11.4])

# Indexing and slicing

Indexing is very useful as it allows you to select specific elements from an array. It also lets you select entire rows/columns or planes as you'll see in future assignments for multidimensional arrays.

# Indexing

Let us select specific elements from the arrays as given.

In [7]:
# selecting the 3rd element,counting starts from 0

a = np.array([1,2,3,4,5])

print(a[2])

print(a[0])

3
1


In [12]:
two_D = np.array(([1,2,3],
             [4,5,6],
             [7,8,9]))

# creating a 2-dimensional NumPy array named two_dim, and then selecting the element at row index 2 and column index 1 (using 0-based indexing) which has the value 8. 
#The syntax used for indexing the 2-D array is two_dim[i][j]

print(two_D[2][1])
print(two_D[2,1])

8
8


# Slicing

In [13]:
# Slice the array a to get the array [2,3,4]
sliced_arr = a[1:4]
print(sliced_arr)

[2 3 4]


In [14]:
# Slice the array a to get the array [1,2,3]
sliced_arr = a[:3]
print(sliced_arr)

[1 2 3]


In [15]:
# Slice the array a to get the array [3,4,5]
sliced_arr = a[2:]
print(sliced_arr)

[3 4 5]


In [16]:
# Slice the array a to get the array [1,3,5]
sliced_arr = a[::2]
print(sliced_arr)

[1 3 5]


# Stacking

Finally, stacking is a feature of NumPy that leads to increased customization of arrays. It means to join two or more arrays, either horizontally or vertically, meaning that it is done along a new axis. 

- `np.vstack()` - stacks vertically
- `np.hstack()` - stacks horizontally
- `np.hsplit()` - splits an array into several smaller arrays

In [20]:
a1 = np.array([[1,1], 
               [2,2]])
a2 = np.array([[3,3],
              [4,4]])
print(f'a1:\n{a1}')
print(f'a2:\n{a2}')

a1:
[[1 1]
 [2 2]]
a2:
[[3 3]
 [4 4]]


In [21]:
# Stack the arrays vertically
vert_stack = np.vstack((a1, a2))
print(vert_stack)

[[1 1]
 [2 2]
 [3 3]
 [4 4]]


In [22]:
# Stack the arrays horizontally
horz_stack = np.hstack((a1, a2))
print(horz_stack)

[[1 1 3 3]
 [2 2 4 4]]


In [23]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

AttributeError: module 'numpy' has no attribute 'zero'